# Generated by Django 4.2.5 on 2023-09-08 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('musician', models.ManyToManyField(related_name='songs', to='music.musician', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('year_of_release', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска')),
                ('musician', models.ManyToManyField(related_name='albums', to='music.musician', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['name', '-year_of_release'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Порядковый номер в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня в альбоме',
                'verbose_name_plural': 'Песни в альбомах',
                'ordering': ['number'],
                'unique_together': {('album', 'song')},
            },
        ),
    ]
