# Generated by Django 4.2.5 on 2023-09-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumsong',
            options={'ordering': ['number_in_album'], 'verbose_name': 'Песня в альбоме', 'verbose_name_plural': 'Песни в альбомах'},
        ),
        migrations.RenameField(
            model_name='albumsong',
            old_name='number',
            new_name='number_in_album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='musician',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='music.AlbumSong', to='music.song', verbose_name='Песни в альбоме'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='musician',
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.musician', verbose_name='Исполнитель'),
            preserve_default=False,
        ),
    ]
