# Generated by Django 4.2.5 on 2023-09-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_albumsong_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', 'song', 'number_in_album')},
        ),
    ]
