# Generated by Django 4.2.5 on 2023-09-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_albumsong_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', 'number_in_album'), ('album', 'song', 'number_in_album')},
        ),
    ]
